### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by nitsuasd** [burhan/e24PaymentPipe-php#1]
Hi Burhan,

Finding your code on git hub was a life saver. I have been tasked with implementation of payment gateway from benefitco and  as you could imagine no sample code for php. After digging around i found your earlier post and then the post from tigerwolf. Just yesterday whilst i was trying to find a bit more information on Benefitco i hit on your e24PaymentPipe implementation which includes support for Benefitco.

Currently since I am in the testing phase. I have setup on on a sub directory called "gateway" of my shared hosting.
I created 3 files namely 
HostedPaymentBuy.php  - using your example copied and updated the code (this is the one that calls e24PaymentPipe.inc.php)
HostedPaymentDetails.php - this is the form that has an action to HostedPaymentBuy.php
failure.php 
Also there is the file your prepared in the same folder
e24PaymentPipe.inc.php 
And the resource file.

File Structure
www.xyz.com/cient/payment/HostedPaymentBuy.php
www.xyz.com/cient/payment/HostedPaymentDetails.php
www.xyz.com/cient/payment/failure.php
www.xyz.com/cient/payment/e24PaymentPipe.inc.php 
www.xyz.com/cient/payment/e24payment/resource.cgn

When i Go to payment details i can see the form the moment i enter my credentials i am taken to HosterPaymentBuy.php as expected
This is the error i get
"Failed to make connection:"

**Comment by burhan** [comment]
If your resource file is new (this terminal is newly setup by your provider), then this code won't work as ACI changed their resource file format. I am working on an update to support the new resource file format.

**Comment by nitsuasd** [comment]
Hi Burhan,
Thanks for the clarification. Is there a quick fix for the same.
Also can I help in any way.

**Comment by wbspot** [comment]
Burhan You are doing well...Do you have any solution about credit card payment integration for Burgan Bank in Kuwait using php java Bridge?
I tried using e24TranPipe but I am always getting -1 ...

**Comment by burhan** [comment]
PHP-Java bridge is overly complicated; use the e24PaymentPipe-PHP version for now. If your terminal is new, I am working on an update of the Python version to support the updated file formats.

Priority is for the Python version; when changes are confirmed there I usually move them to the PHP client as well.

**Comment by wbspot** [comment]
Thanx for your feedback. I already done successfully KNET integration using php-Javabridge after some testing and wasting of time. Now I am going to Integrate Visa Card. Do you have any idea what field we need to pass and what things we have to do.I read their ACI Docs I used e24TranPipe instead of e24PaymentPipe because E24PaymentPipe for hosted payment getway like Knet. Any way output is always showing -1 means failure.

**Comment by burhan** [comment]
KNET only supports debit cards, not credit cards. Check with the bank providing the gateway.

**Comment by wbspot** [comment]
Sorry I did not define the Bank Name. Actually I am doing for Burgan bank not KNET. Just they given me one pdf file  http://mygulfweb.com/uploads/Merchant_Integration_Guide.pdf

**Comment by burhan** [comment]
For the TranPipe, there are these extra parameters (in addition to the normal amount, currencycode, resource path, alias and UDF1-5)
- `Type` (this should be `CC`)
- `Cvv2`

The following three if you are capturing the card on your end, or doing testing:
- `ExpMonth`
- `ExpYear`
- `Card`

The result should be the string `captured` for successful transactions.

Then, its the same logic of redirection.

**Comment by wbspot** [comment]
Yes you are right I am using same what its written in pdf.

```
                   $pipe->setAction("2"); 
        $pipe->setAlias("t1602");
        $pipe->setAmt("2");
        $pipe->setCard("5522993139767002");
        $pipe->setType("CC");
        $pipe->setCurrencyCode("414");
        $pipe->setCvv2("110");
        $pipe->setExpMonth("11");
        $pipe->setExpYear("2015");
        $pipe->setMember("MC W Charge");

        $pipe->setResourcePath("D:\\Globmed\\");
        //$pipe->setSSL(1);

        $pipe->setRef("001");
        $pipe->setAddress("Hawally");
        $pipe->setTrackId("1");
        $pipe->setTransId("123");
        $pipe->setUdf1("a");
        $pipe->setUdf2("b");
        $pipe->setUdf3("c");
        $pipe->setUdf4("d");
        $pipe->setUdf5("56");
        $pipe->setZip("3000");
                    $pipe->performTransaction();
```

Please check is there any missing?
